window.EARTH_HERO_CONFIG = {
  API_URL: "https://script.google.com/macros/s/AKfycbx0o-StzFrRBun9tEhDXhfpf8QGMRM-bg94d1wVIYPk8Nr26az4YwzPpIYHlLj_NFoX/exec",
  BRANCHES: [
    "A11 Residential - PHL2",
    "A62 Central People Development Center",
    "AYY Central Ayutthaya",
    "BBN Market Place Bangbon",
    "BNA Central Bangna",
    "CBR Central Chonburi",
    "CMA Central Chiangmai Airport",
    "CMI Central Chiangmai",
    "CMP Commercial Platform",
    "CRI Central Chiangrai",
    "CTR Central Chanthaburi",
    "CTW centralwOrld",
    "CWG Central Westgate",
    "CWN Central Chaengwattana",
    "CWT centralwOrld Offices",
    "DST Market Place Dusit",
    "EKM Ekkamai Lifestyle Center",
    "ESP Esplanade Ratchadapisek",
    "GOH GO HOTEL",
    "GTW G Tower Grand Rama 9",
    "HOF HOF",
    "HYI Central Hatyai",
    "ICY Central i-City",
    "JAV Market Place Thonglor",
    "KBI Central Krabi",
    "KKC Central Khon Kaen Campus",
    "KKN Central Khonkaen",
    "KTK Market Place Krungthep Kreeta",
    "LAV Market Place - La Villa",
    "LPG Central Lampang",
    "LPO Central Ladprao",
    "MHC Central Mahachai",
    "NKM Central Korat",
    "NKR Central Nakhon Si",
    "NKT Central Nakhonpathom",
    "NKW Central Nakhonsawan",
    "NTG The Ninth Towers Grand Rama 9",
    "PCU Market Place Pracha Uthit",
    "PK2 Central Phuket Floresta",
    "PKO Central Pinklao",
    "PKS Petchkasem Power Center",
    "PKT Central Phuket Festival",
    "PNL Central Phitsanulok",
    "PTB Central Pattaya",
    "PTC Central Marina",
    "PTY Market Place Pattaya",
    "RCP Central Westville",
    "RID Central Ramindra",
    "RM2 Central Rama 2",
    "RM3 Central Rama 3",
    "RM4 Central Park",
    "RM9 Central Rama 9",
    "RTB Central Rattanathibet",
    "RYG Central Rayong",
    "RYT The Avenue Ratchayothin",
    "SLY Central Salaya",
    "SMI Central Samui",
    "SRC Central Si Racha",
    "SRT Central Suratthani",
    "SVB Central Village",
    "THL Marche Thonglor",
    "UBN Central Ubon",
    "UDN Central Udon",
    "UHG Unilever House Grand Rama 9",
    "อื่น ๆ"
  ]
};
